### PR TITLE
Create client input error messages

### PR DESCRIPTION
**Pull request by oliveiraigorm**
### Changes

Adds message warnings to input fields, align footer buttons

### Testing

Try to create a client without a name, invalid email and invalid phone number

### Screenshot
image

### CODE REVIEW

**Comment by oliveiraigorm** [comment]
> Overall looks good, but I think we should also get this implemented on the edit form for a client, so the experience is the same.

Me too, should I do it on this card or create a new one?

**Comment by mwalbeck** [comment]
You can go ahead and do it here

**Review by mwalbeck — COMMENTED** [review]
To add to this, while we're working with the validation.

When editing the age, if you input letters it'll show a red border to indicate a problem, though not any message about what the problem is. If you then hit update while there are letters in the age field, it lets you submit, but then it just removes the letter from the field.

I think it would be better if the validation prevented submitting if there are letters in the age field, but allows it to be a number or empty.

**Comment by oliveiraigorm** [comment]
> To add to this, while we're working with the validation.
> 
> When editing the age, if you input letters it'll show a red border to indicate a problem, though not any message about what the problem is. If you then hit update while there are letters in the age field, it lets you submit, but then it just removes the letter from the field.
> 
> I think it would be better if the validation prevented submitting if there are letters in the age field, but allows it to be a number or empty.

The input type on FIrefox wasn't working. I've added the message and removed the input type, since it wasn't causing issues with the new validation.

**Review by mwalbeck — APPROVED** [review]

**Pull request merged**
